:toc:
:numbered:
:data-uri:

<<junk,echo=FALSE>>=    Somehow, this avoids the "figure margins too large" error ~kbroman
par(mar=rep(0,4))
@

<<options, echo=FALSE, eval = TRUE, echo = FALSE>>=
  options(width=75, continue = " ")
  library("Bureau")
@ 
== RVSharing Examples ==

Let's look at some simple pedigree structures.

=== Siblings ===

<<RVsharing.toy2, eval = TRUE, echo = TRUE>>=
id <- paste0("sub", 1:4)
fa.id <- c(NA,NA,"sub1","sub1")
ma.id <- c(NA,NA,"sub2","sub2")
test.ped.siblings <- pedigree(id = id, dadid = fa.id, momid = ma.id, sex = c(1,2,1,2))
@ 
<<plotped, fig = TRUE, width = 3, eval = TRUE, echo = FALSE>>=
plot(test.ped.siblings)
@ 
Apply the RVsharing method using a pedigree object, three id vectors, or by directly calling the non-exported function "RVsharing.fn" defined in  "rare_variant_sharing_v3.R".
<<sibs>>=
RVsharing(test.ped.siblings)$pshare
RVsharing(id = id, dad.id = fa.id, mom.id = ma.id )$pshare
Bureau:::RVsharing.fn(id = id, dad.id = fa.id, mom.id = ma.id )$pshare
1/3
@ 
=== First Cousins ===
<<RVsharing.toy2, eval = TRUE, echo = TRUE>>=
id <- paste0("sub", 1:8)
fa.id <- c(NA,NA,NA,"sub1","sub1", NA,"sub3","sub5")
ma.id <- c(NA,NA,NA,"sub2","sub2", NA,"sub4","sub6")
test.ped.first.cousins <- pedigree(id = id, dadid = fa.id, momid = ma.id, sex = c(1,2,1,2,1,2,2,2))
@ 
<<plotped2, fig = TRUE, width = 3, eval = TRUE, echo = FALSE>>=
plot(test.ped.first.cousins)
@ 
<<test3>>=
RVsharing(id = id, dad.id = fa.id, mom.id = ma.id )$pshare
RVsharing(test.ped.first.cousins)$pshare
Bureau:::RVsharing.fn(id = id, dad.id = fa.id, mom.id = ma.id )$pshare
1/15
@ 

=== Second Cousins ===
<<RVsharing.toy3, eval = TRUE, echo = TRUE>>=
id <- paste0("sub", 1:12)
fa.id <- c(NA,NA,NA,"sub1","sub1", NA,"sub3","sub5",NA,NA,"sub9","sub10")
ma.id <- c(NA,NA,NA,"sub2","sub2", NA,"sub4","sub6",NA,NA,"sub7","sub8")
test.ped.second.cousins <- pedigree(id = id, dadid = fa.id, momid = ma.id, sex = c(1,2,1,2,1,2,2,2,1,1,2,2))
@ 

<<plotped3, fig = TRUE, width = 3, eval = TRUE, echo = FALSE>>=
plot(test.ped.second.cousins)
@ 

<<test5, echo = TRUE, eval = TRUE>>=
RVsharing(id = id, dad.id = fa.id, mom.id = ma.id )$pshare
RVsharing(ped = test.ped.second.cousins )$pshare
Bureau:::RVsharing.fn(id = id, dad.id = fa.id, mom.id = ma.id )$pshare
1/63
@
